### ISSUE TITLE
Configure authorization mode

### ISSUE THREAD

**Issue by pkl** [douglasjunior/react-native-get-location#3]
Nice code!

Would it make sense to add a config option where we can choose between requestAlwaysAuthorization and requestWhenInUseAuthorization?

This should in theory make it possible to request the location in the background e.g by "waking up" the application by sending a PushKit message to it and call this library.

Cheers,
Per

**Comment by douglasjunior** [comment]
Hi, thanks for the feedback.

This needs to be discussed. Because, this library don't have watch mode and React Native don't have a nice way to "run in background".

So, for now, I think that is better to request this permission using a specific library such as [react-native-permissions](https://github.com/yonahforst/react-native-permissions)
